package org.example.client.common;

public enum CommandType {

    LOGIN,
    LOGOUT,
    REGISTER,
    CHANGE_PASSWORD,
    GET_PROFILE,

    GET_ALL_DOCTORS,

    GET_SLOTS,
    GET_DOCTOR_SCHEDULE,

    BOOK_APPOINTMENT,
    CANCEL_APPOINTMENT,
    GET_MY_APPOINTMENTS,
    GET_ALL_APPOINTMENTS,

    GET_HISTORY,
    SAVE_DIAGNOSIS,

    UPDATE_REMINDER,
    CANCEL_REMINDER,
    GET_REMINDERS,
    GET_PATIENT_BY_ID,
    SEARCH_PATIENTS,
    UPDATE_PATIENT,

    GET_ALL_USERS,
    BLOCK_USER,
    UNBLOCK_USER,
    DELETE_USER,
    UPDATE_DOCTOR,
    GET_AUDIT_LOG,

    PING,
}
