package common;

public enum CommandType {

    LOGIN,
    LOGOUT,
    REGISTER,
    CHANGE_PASSWORD,
    GET_PROFILE,

    GET_ALL_DOCTORS,
    GET_DOCTORS_BY_SPEC,
    GET_DOCTOR_BY_ID,
    GET_SPECIALIZATIONS,

    GET_SLOTS,
    GET_DOCTOR_SCHEDULE,
    SET_SCHEDULE,
    BLOCK_SLOT,
    UNBLOCK_SLOT,

    BOOK_APPOINTMENT,
    CANCEL_APPOINTMENT,
    RESCHEDULE_APPOINTMENT,
    CONFIRM_APPOINTMENT,
    MARK_COMPLETED,
    MARK_MISSED,
    GET_MY_APPOINTMENTS,
    GET_ALL_APPOINTMENTS,
    GET_APPOINTMENT_BY_ID,

    GET_HISTORY,
    GET_APPOINTMENT_DETAILS,
    SAVE_DIAGNOSIS,

    GET_REMINDERS,
    CREATE_REMINDER,
    UPDATE_REMINDER,
    CANCEL_REMINDER,
    TOGGLE_REMINDER,

    GET_PATIENT_BY_ID,
    SEARCH_PATIENTS,
    UPDATE_PATIENT,

    GET_ALL_USERS,
    CREATE_USER,
    UPDATE_USER,
    BLOCK_USER,
    UNBLOCK_USER,
    DELETE_USER,
    ADD_DOCTOR,
    UPDATE_DOCTOR,
    REMOVE_DOCTOR,
    GET_AUDIT_LOG,

    PING,
    SERVER_ERROR,
    UNKNOWN
}
